# This is a basic workflow to help you get started with Actions

name: Darcher Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0
          
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '8'
          
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      
      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
          
      - name: Setup chrome driver
        uses: nanasess/setup-chromedriver@master
        
      - name: Download ChromeProfile
        run: |
          wget https://github.com/Troublor/darcher/releases/download/v1.0.0/ChromeProfile.tar.gz
          tar -xvzf ChromeProfile.tar.gz
          
      - name: Download ethash
        run: wget https://zenodo.org/record/4893187/files/ethash.tar?download=1 -O ethash.tar
          
      - name: Extract ethash
        run: tar -xvf ethash.tar
      
      - name: ls
        run: echo | ls
        
      - name: Setup Project
        run: yarn
      
      - name: Build project
        run: yarn build
      
      - name: test AgroChain
        run: yarn workspace @darcher/examples experiment:AgroChain
